name: Deploy to Vercel

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Godot
      run: |
        wget -q https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
        unzip -q Godot_v4.4.1-stable_linux.x86_64.zip
        chmod +x Godot_v4.4.1-stable_linux.x86_64
        sudo mv Godot_v4.4.1-stable_linux.x86_64 /usr/local/bin/godot
        
        # Download export templates
        wget -q https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
        mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable
        unzip -q Godot_v4.4.1-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/4.4.1.stable
        mv ~/.local/share/godot/export_templates/4.4.1.stable/templates/* ~/.local/share/godot/export_templates/4.4.1.stable/
        rmdir ~/.local/share/godot/export_templates/4.4.1.stable/templates
        
    - name: Verify Godot installation
      run: |
        godot --version
        
    - name: Import project
      run: |
        godot --headless --import --path .
        
    - name: Export for Web
      run: |
        mkdir -p dist
        godot --headless --export-release "Web" dist/index.html --path .
        
    - name: List export contents
      run: |
        ls -la dist/
        
    - name: Deploy to Vercel
      if: ${{ secrets.VERCEL_TOKEN }}
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./dist
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: dist/
        retention-days: 30